## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

jobs:
  include:
    - stage: Testing Julia v1.1
      julia: 1.1
      os: linux
      branches:
        only:
          - master
          - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

    - stage: Documentation
      julia: 1.1
      os: linux
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - cd $HOME; if [[ ! -d cmdstan ]]; then git clone https://github.com/stan-dev/cmdstan.git; fi
        - cd $HOME/cmdstan; git checkout v2.18.1; make stan-update; make build
        - export JULIA_CMDSTAN_HOME=$HOME/cmdstan
        - cd $TRAVIS_BUILD_DIR
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip

    - stage: Testing Julia v1.0
      julia: 1.0
      os: linux
      branches:
        only:
          - master
          - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: true

git:
  depth: 99999999

