## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx
  
julia:
  - 1.0
  #- 1.1
  #- nightly
  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - cd $HOME; if [[ ! -d cmdstan ]]; then git clone https://github.com/stan-dev/cmdstan.git; fi
  - cd $HOME/cmdstan; git checkout v2.18.0; make stan-update; make build
  - export JULIA_CMDSTAN_HOME=$HOME/cmdstan
  - cd $TRAVIS_BUILD_DIR
  - julia -e 'using Pkg; Pkg.test("StatisticalRethinking"; coverage=true)'
  - julia --color=yes docs/make.jl

matrix:
  allow_failures:
    - os: osx
    - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl

notifications:
  email: true

git:
  depth: 99999999

