name = "StatisticalRethinking"
uuid = "2d09df54-9d0f-5258-8220-54c2a3d4fbee"
authors = ["Rob J Goedman <goedman@mac.com>"]
version = "2.2.4"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StanOptimize = "fbd8da12-e93d-5a64-9231-612a0707ab99"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
CSV = "0.5, 0.6"
DataFrames = "0.20, 0.21"
Distributions = "0.22, 0.23"
DocStringExtensions = "0.8"
KernelDensity = "0.5"
LaTeXStrings = "1.1"
MCMCChains = "3.0, 4.0"
MonteCarloMeasurements = "0.8, 0.9"
NamedArrays = "0.9"
Parameters = "0.12"
Reexport = "0.2"
Requires = "1.0"
StanOptimize = "2.0"
StanSample = "2.0"
StatsBase = "0.32, 0.33"
StatsFuns = "0.9"
StatsPlots = "0.14"
UnicodePlots = "1.2"
julia = "1"
