name = "StatisticalRethinking"
uuid = "2d09df54-9d0f-5258-8220-54c2a3d4fbee"
authors = ["Rob J Goedman <goedman@mac.com>"]
version = "2.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MCMCDiagnostics = "6e857e4b-079a-58c4-aeab-bc2670384359"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StanBase = "d0ee94f6-a23d-54aa-bbe9-7f572d6da7f5"
StanOptimize = "fbd8da12-e93d-5a64-9231-612a0707ab99"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"

[compat]
CSV = "0.5"
CategoricalArrays = "0.7"
DataFrames = "0.20"
DataStructures = "0.14, 0.15, 0.16, 0.17"
Distributions = "0.21, 0.22"
Documenter = "0.24"
DynamicHMC = "2.1"
GLM = "1.3"
GR = "0.42, 0.43, 0.44"
JLD = "0.9"
KernelDensity = "0.5"
LogDensityProblems = "0.9, 0.10"
MCMCChains = "0.4, 1.0"
MCMCDiagnostics = "0.3"
MonteCarloMeasurements = "0.5, 0.6, 0.7"
Optim = "0.18, 0.19, 0.20"
Parameters = "0.12"
Plots = "0.27, 0.28"
RDatasets = "0.6"
Reexport = "0.2"
StanBase = "1.1, 2.0"
StanOptimize = "1.1, 2.0"
StanSample = "1.1, 2.0"
StatsBase = "0.32"
StatsFuns = "0.7, 0.9"
StatsPlots = "0.12, 0.13"
TransformVariables = "0.3"
julia = "1"
