name = "StatisticalRethinking"
uuid = "2d09df54-9d0f-5258-8220-54c2a3d4fbee"
authors = ["Rob J Goedman <goedman@mac.com>"]
version = "0.3.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CmdStan = "593b3428-ca2f-500c-ae53-031589ec8ddd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MCMCChain = "1671dc4f-43c8-512c-ab25-e1704a74065e"
Mamba = "5424a776-8be3-5c5b-a13f-3551f69ba0e6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StanMCMCChain = "8f1571ae-b3a1-52af-8ab1-32258739efdb"
StatPlots = "60ddc479-9b66-56df-82fc-76a74619b69c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
