name = "StatisticalRethinking"
uuid = "2d09df54-9d0f-5258-8220-54c2a3d4fbee"
authors = ["Rob J Goedman <goedman@mac.com>"]
version = "3.2.6"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
BSplines = "488c2830-172b-11e9-1591-253b8a7df96d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ParetoSmoothedImportanceSampling = "98f080ec-61e2-11eb-1c7b-31ea1097256f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StructuralCausalModels = "a41e6734-49ce-4065-8b83-aff084c01dfd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
AxisArrays = "0.4"
BSplines = "0.2, 0.3"
CSV = "0.5, 0.6, 0.7, 0.8"
DataFrames = "0.21, 0.22"
Distributions = "0.22, 0.23, 0.24"
DocStringExtensions = "0.8"
Formatting = "0.4"
GLM = "^1.3"
KernelDensity = "0.5, 0.6"
LaTeXStrings = "1.1"
MCMCChains = "4.0"
MonteCarloMeasurements = "0.8, 0.9, 1.0, 0.10"
NamedArrays = "0.9"
NamedTupleTools = "0.13"
Optim = "0.20, 1.2"
OrderedCollections = "1.3"
Parameters = "0.12"
ParetoSmoothedImportanceSampling = "0.1"
PrettyTables = "0.9, 0.10, 0.11"
Reexport = "0.2, 1.0"
Requires = "1.0"
StatsBase = "0.32, 0.33"
StatsFuns = "0.9"
StatsPlots = "0.14"
StructuralCausalModels = "1.0"
julia = "1"
