name = "StatisticalRethinking"
uuid = "2d09df54-9d0f-5258-8220-54c2a3d4fbee"
version = "4.5.3"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ParetoSmoothedImportanceSampling = "98f080ec-61e2-11eb-1c7b-31ea1097256f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StructuralCausalModels = "a41e6734-49ce-4065-8b83-aff084c01dfd"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CSV = "0.9, 0.10"
DataFrames = "1"
Distributions = "0.25"
DocStringExtensions = "0.8, 0.9"
Documenter = "0.27"
Formatting = "0.4"
KernelDensity = "0.6"
MCMCChains = "5.0"
MonteCarloMeasurements = "1.0"
NamedArrays = "0.9"
NamedTupleTools = "0.13, 0.14"
Optim = "1.5"
OrderedCollections = "1.4"
Parameters = "0.12"
ParetoSmoothedImportanceSampling = "1"
PrettyTables = "1.0, 2.0"
Reexport = "1.2"
Requires = "1.0"
StatsBase = "0.33"
StatsFuns = "0.8, 0.9, 1.0"
StructuralCausalModels = "1"
Tables = "1.5"
julia = "1"

[extras]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
ParetoSmooth = "a68b5a21-f429-434e-8bfa-46b447300aac"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StanSample", "AxisKeys", "ParetoSmooth", "Test"]
